;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        TeX-insert-backslash
        TeX-insert-dollar
        TeX-insert-sub-or-superscript
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-pound
        c-electric-semi&comma
        c-electric-slash
        c-electric-star
        c-indent-line-or-region
        company-indent-or-complete-common
        eri-indent
        erlang-electric-comma
        evil-numbers/dec-at-pt
        evil-numbers/inc-at-pt
        fill-paragraph
        haskell-indentation-delete-backward-char
        haskell-indentation-delete-char
        ido-switch-buffer
        indent-for-tab-command
        kill-or-join-next-line
        kmacro-end-or-call-macro
        kmacro-start-macro-or-insert-counter
        mc-search-backward
        mc-search-forward
        nav-forward-blank-line
        nav-half-page-down
        nav-half-page-up
        nav-next-line
        nav-previous-line
        open-line-above
        overwrite-mode
        prelude-move-beginning-of-line
        sgml-close-tag
        sgml-slash
        subword-left
        subword-right
        tex-insert-quote
        whole-line-or-region-comment-dwim-3
        whole-line-or-region-kill-region
        whole-line-or-region-kill-ring-save
        whole-line-or-region-yank
        yaml-electric-backspace
        yaml-electric-bar-and-angle
        yaml-electric-dash-and-dot
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        duplicate-current-line-or-region
        end-of-buffer
        mc/mark-all-in-region
        minimap-mode
        previous-buffer
        ))
